# Generated by Django 5.2.8 on 2025-11-30 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('confidence', models.FloatField(default=0.0)),
                ('sources', models.JSONField(default=list)),
                ('commitments', models.JSONField(default=list)),
                ('parameters', models.JSONField(default=dict)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Query History',
                'verbose_name_plural': 'Query History',
                'ordering': ['-created_at'],
            },
        ),
    ]
